version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - MIX_ENV=dev
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      sh -c "mix ecto.create && mix phx.server"
    restart: always

  db:
    image: postgres:15.1
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
